import { copyToClipboard } from '../utils/clipboard.js';
import { showNotification } from '../utils/notify.js';
import { createElement, clearElement } from '../utils/dom.js';

// DATABÁZE EMOJI S ČESKÝMI KLÍČOVÝMI SLOVY
const emojiDatabase = [
    // ==========================================
    // 1. 😀 SMAJLÍCI A EMOCE
    // ==========================================
    { char: '😀', category: 'smajlici', keywords: ['usměv', 'smajlík', 'happy', 'veselý', 'úsměv', 'radost'] },
    { char: '😃', category: 'smajlici', keywords: ['usměv', 'otevřená', 'pusa', 'happy'] },
    { char: '😄', category: 'smajlici', keywords: ['usměv', 'otevřené', 'oči', 'happy'] },
    { char: '😁', category: 'smajlici', keywords: ['usměv', 'zuby', 'happy'] },
    { char: '😆', category: 'smajlici', keywords: ['smích', 'směje', 'zavřené', 'oči', 'lol'] },
    { char: '😅', category: 'smajlici', keywords: ['pot', 'nervozní', 'studený', 'smích'] },
    { char: '😂', category: 'smajlici', keywords: ['brečí', 'smích', 'slzy', 'legrace', 'pláč'] },
    { char: '🤣', category: 'smajlici', keywords: ['brečí', 'smích', 'slzy', 'valí', 'kotálí'] },
    { char: '😊', category: 'smajlici', keywords: ['milý', 'sladký', 'šťastný', 'červenání'] },
    { char: '😇', category: 'smajlici', keywords: ['anděl', 'svatý', 'nevinný', 'halo'] },
    { char: '🙂', category: 'smajlici', keywords: ['mírný', 'usměv', 'neutrální'] },
    { char: '🙃', category: 'smajlici', keywords: ['obrácený', 'na hlavu', 'sarkasmus'] },
    { char: '😉', category: 'smajlici', keywords: ['mrknutí', 'mrk', 'pomrknutí', 'naznačení'] },
    { char: '😌', category: 'smajlici', keywords: ['ulevený', 'klid', 'relax', 'úleva'] },
    { char: '😍', category: 'smajlici', keywords: ['zamilovaný', 'láska', 'srdce', 'oči'] },
    { char: '🥰', category: 'smajlici', keywords: ['zamilovaný', 'láska', 'srdce', 'roztomilý'] },
    { char: '😘', category: 'smajlici', keywords: ['pusa', 'líbání', 'polibek', 'love'] },
    { char: '😗', category: 'smajlici', keywords: ['pusa', 'pískání', 'líbání'] },
    { char: '😙', category: 'smajlici', keywords: ['pusa', 'líbání', 'šťastný'] },
    { char: '😚', category: 'smajlici', keywords: ['pusa', 'líbání', 'zavřené', 'oči'] },
    { char: '😋', category: 'smajlici', keywords: ['mňam', 'chutná', 'dobré', 'jídlo'] },
    { char: '😛', category: 'smajlici', keywords: ['jazyk', 'škádlí', 'provokace'] },
    { char: '😝', category: 'smajlici', keywords: ['jazyk', 'škádlí', 'zavřené', 'oči'] },
    { char: '😜', category: 'smajlici', keywords: ['jazyk', 'mrknutí', 'blbnutí'] },
    { char: '🤪', category: 'smajlici', keywords: ['blázen', 'šílený', 'crazy'] },
    { char: '🤨', category: 'smajlici', keywords: ['podezření', 'zkoumavý', 'kdo'] },
    { char: '🧐', category: 'smajlici', keywords: ['monokl', 'pátravý', 'detektiv'] },
    { char: '🤓', category: 'smajlici', keywords: ['brýle', 'nerd', 'chytrý'] },
    { char: '😎', category: 'smajlici', keywords: ['brýle', 'cool', 'stylový', 'sluneční'] },
    { char: '🥸', category: 'smajlici', keywords: ['převlek', 'maskování', 'inkognito'] },
    { char: '🤩', category: 'smajlici', keywords: ['hvězdy', 'nadšený', 'úžas', 'wow'] },
    { char: '🥳', category: 'smajlici', keywords: ['oslava', 'party', 'narozeniny'] },
    { char: '😏', category: 'smajlici', keywords: ['úšklebek', 'nadřazený', 'vím své'] },
    { char: '😒', category: 'smajlici', keywords: ['naštvaný', 'otrávený', 'unuděný'] },
    { char: '😞', category: 'smajlici', keywords: ['smutný', 'zklamaný', 'deprese'] },
    { char: '😔', category: 'smajlici', keywords: ['smutný', 'zamyšlený', 'lítost'] },
    { char: '😟', category: 'smajlici', keywords: ['znepokojený', 'starost', 'obavy'] },
    { char: '😕', category: 'smajlici', keywords: ['zmatený', 'nejistý', 'cože'] },
    { char: '🙁', category: 'smajlici', keywords: ['smutný', 'mírně', 'zklamaný'] },
    { char: '☹️', category: 'smajlici', keywords: ['smutný', 'zamračený'] },
    { char: '😣', category: 'smajlici', keywords: ['muka', 'bolest', 'trápení'] },
    { char: '😖', category: 'smajlici', keywords: ['zmatený', 'frustrovaný'] },
    { char: '😫', category: 'smajlici', keywords: ['unavený', 'vyčerpaný'] },
    { char: '😩', category: 'smajlici', keywords: ['unavený', 'vyčerpaný', 'padá'] },
    { char: '🥺', category: 'smajlici', keywords: ['prosím', 'štěňátko', 'roztomilý'] },
    { char: '😢', category: 'smajlici', keywords: ['brečí', 'slza', 'smutný'] },
    { char: '😭', category: 'smajlici', keywords: ['brečí', 'slzy', 'hodně', 'pláč'] },
    { char: '😤', category: 'smajlici', keywords: ['frustrace', 'kouř', 'nosem'] },
    { char: '😠', category: 'smajlici', keywords: ['naštvaný', 'zlost'] },
    { char: '😡', category: 'smajlici', keywords: ['naštvaný', 'zlost', 'rudý'] },
    { char: '🤬', category: 'smajlici', keywords: ['nadávky', 'symboly', 'hněv'] },
    { char: '😈', category: 'smajlici', keywords: ['čert', 'ďábel', 'zlo'] },
    { char: '👿', category: 'smajlici', keywords: ['čert', 'ďábel', 'naštvaný'] },
    { char: '💀', category: 'smajlici', keywords: ['kostlivec', 'smrt', 'umřít'] },
    { char: '☠️', category: 'smajlici', keywords: ['lebka', 'smrt', 'nebezpečí'] },
    { char: '💩', category: 'smajlici', keywords: ['hovno', 'kakání', 'sranda'] },
    { char: '🤡', category: 'smajlici', keywords: ['klaun', 'cirkus', 'sranda'] },
    { char: '👹', category: 'smajlici', keywords: ['příšera', 'ogre', 'monstrum'] },
    { char: '👺', category: 'smajlici', keywords: ['goblín', 'příšera', 'japonský'] },
    { char: '👻', category: 'smajlici', keywords: ['duch', 'strašidlo', 'halloween'] },
    { char: '👽', category: 'smajlici', keywords: ['mimozemšťan', 'ufo', 'alien'] },
    { char: '🤖', category: 'smajlici', keywords: ['robot', 'android', 'ai'] },
    { char: '😺', category: 'smajlici', keywords: ['kočka', 'usměv', 'kočičí'] },
    { char: '😸', category: 'smajlici', keywords: ['kočka', 'smích', 'legrace'] },
    { char: '😹', category: 'smajlici', keywords: ['kočka', 'brečí', 'smích', 'slzy'] },
    { char: '😻', category: 'smajlici', keywords: ['kočka', 'zamilovaný', 'láska'] },
    { char: '😼', category: 'smajlici', keywords: ['kočka', 'úšklebek', 'namyšlený'] },
    { char: '😽', category: 'smajlici', keywords: ['kočka', 'pusa', 'líbání'] },
    { char: '🙀', category: 'smajlici', keywords: ['kočka', 'překvapení', 'zděšení'] },
    { char: '😿', category: 'smajlici', keywords: ['kočka', 'brečí', 'smutný'] },
    { char: '😾', category: 'smajlici', keywords: ['kočka', 'naštvaný', 'zlost'] },
    { char: '🫨', category: 'smajlici', keywords: ['třesení', 'otřes', 'shaking'] },
    { char: '🫩', category: 'smajlici', keywords: ['unavený', 'oči', 'exhausted'] },
    { char: '🫦', category: 'smajlici', keywords: ['kousání', 'rty', 'bite'] },
    { char: '🫤', category: 'smajlici', keywords: ['nakřivo', 'nejistý'] },
    { char: '🫱', category: 'smajlici', keywords: ['ruka', 'vpravo'] },
    { char: '🫲', category: 'smajlici', keywords: ['ruka', 'vlevo'] },
    { char: '🫳', category: 'smajlici', keywords: ['ruka', 'dolů'] },
    { char: '🫴', category: 'smajlici', keywords: ['ruka', 'nahoru'] },
    { char: '🫰', category: 'smajlici', keywords: ['prsty', 'srdce'] },
    { char: '🫵', category: 'smajlici', keywords: ['ukazování', 'prst', 'ty'] },
    { char: '🫶', category: 'smajlici', keywords: ['srdce', 'rukou'] },
    { char: '🫷', category: 'smajlici', keywords: ['zastavení', 'ruka', 'vlevo'] },
    { char: '🫸', category: 'smajlici', keywords: ['zastavení', 'ruka', 'vpravo'] },
    { char: '🙇', category: 'smajlici', keywords: ['uklon', 'omluva'] },
    { char: '💁', category: 'smajlici', keywords: ['informace', 'ruka'] },
    { char: '🙅', category: 'smajlici', keywords: ['zákaz', 'ne', 'ruka'] },
    { char: '🙆', category: 'smajlici', keywords: ['ano', 'ok', 'ruka'] },
    { char: '🙋', category: 'smajlici', keywords: ['hlášení', 'ruka', 'zvednutá'] },
    { char: '🙎', category: 'smajlici', keywords: ['naštvaný', 'pusa'] },
    { char: '🙍', category: 'smajlici', keywords: ['skleslý', 'shrnout'] },
    { char: '💆', category: 'smajlici', keywords: ['masáž', 'head massage'] },
    { char: '💇', category: 'smajlici', keywords: ['kadeřník', 'haircut'] },
    { char: '🚶', category: 'smajlici', keywords: ['chůze', 'jít'] },
    { char: '🏃', category: 'smajlici', keywords: ['běh', 'utíkat'] },
    { char: '💃', category: 'smajlici', keywords: ['tanec', 'žena'] },
    { char: '🕺', category: 'smajlici', keywords: ['tanec', 'muž'] },
    { char: '👯', category: 'smajlici', keywords: ['králičí', 'ucho', 'party'] },
    { char: '🧖', category: 'smajlici', keywords: ['sauna', 'pařit'] },
    { char: '🧗', category: 'smajlici', keywords: ['lezení', 'hora'] },
    { char: '🧘', category: 'smajlici', keywords: ['jóga', 'meditace'] },
    { char: '🛀', category: 'smajlici', keywords: ['koupel', 'vana'] },
    { char: '🛌', category: 'smajlici', keywords: ['spaní', 'postel'] },

    // ==========================================
    // 2. ❤️ SRDCE A SYMBOLY
    // ==========================================
    { char: '❤️', category: 'srdce', keywords: ['srdce', 'láska', 'červená'] },
    { char: '🧡', category: 'srdce', keywords: ['srdce', 'oranžová'] },
    { char: '💛', category: 'srdce', keywords: ['srdce', 'žlutá'] },
    { char: '💚', category: 'srdce', keywords: ['srdce', 'zelená'] },
    { char: '💙', category: 'srdce', keywords: ['srdce', 'modrá'] },
    { char: '💜', category: 'srdce', keywords: ['srdce', 'fialová'] },
    { char: '🖤', category: 'srdce', keywords: ['srdce', 'černá'] },
    { char: '🤍', category: 'srdce', keywords: ['srdce', 'bílá'] },
    { char: '🤎', category: 'srdce', keywords: ['srdce', 'hnědá'] },
    { char: '💔', category: 'srdce', keywords: ['zlomené', 'srdce', 'bolest'] },
    { char: '❤️‍🔥', category: 'srdce', keywords: ['srdce', 'oheň', 'vášeň'] },
    { char: '❤️‍🩹', category: 'srdce', keywords: ['srdce', 'obvaz', 'uzdravení'] },
    { char: '💌', category: 'srdce', keywords: ['dopis', 'láska', 'obálka'] },
    { char: '💕', category: 'srdce', keywords: ['dvě', 'srdce'] },
    { char: '💞', category: 'srdce', keywords: ['kroužící', 'srdce'] },
    { char: '💓', category: 'srdce', keywords: ['bušící', 'srdce'] },
    { char: '💗', category: 'srdce', keywords: ['rostoucí', 'srdce'] },
    { char: '💖', category: 'srdce', keywords: ['třpytivé', 'srdce'] },
    { char: '💘', category: 'srdce', keywords: ['šíp', 'cupid', 'zamilovaný'] },
    { char: '💝', category: 'srdce', keywords: ['stuha', 'srdce'] },
    { char: '💟', category: 'srdce', keywords: ['ozdoba', 'srdce'] },
    { char: '❣️', category: 'srdce', keywords: ['vykřičník', 'srdce'] },
    { char: '💯', category: 'symboly', keywords: ['sto', 'stoprocentní'] },
    { char: '✨', category: 'symboly', keywords: ['hvězdy', 'magie', 'třpyt'] },
    { char: '⭐', category: 'symboly', keywords: ['hvězda'] },
    { char: '🌟', category: 'symboly', keywords: ['zářící', 'hvězda'] },
    { char: '💫', category: 'symboly', keywords: ['závrať', 'magie'] },
    { char: '🔥', category: 'symboly', keywords: ['oheň', 'žhavé', 'populární'] },
    { char: '💥', category: 'symboly', keywords: ['exploze', 'rána'] },
    { char: '💨', category: 'symboly', keywords: ['vítr', 'utíká'] },
    { char: '💦', category: 'symboly', keywords: ['pot', 'voda', 'kapičky'] },
    { char: '💧', category: 'symboly', keywords: ['kapka', 'voda'] },
    { char: '🎯', category: 'symboly', keywords: ['terč', 'cíl', 'přesně'] },
    { char: '✅', category: 'symboly', keywords: ['fajfka', 'hotovo'] },
    { char: '❌', category: 'symboly', keywords: ['křížek', 'špatně'] },
    { char: '❓', category: 'symboly', keywords: ['otazník'] },
    { char: '❗', category: 'symboly', keywords: ['vykřičník', 'důležité'] },
    { char: '‼️', category: 'symboly', keywords: ['dva', 'vykřičníky'] },
    { char: '⁉️', category: 'symboly', keywords: ['otazník', 'vykřičník'] },
    { char: '💢', category: 'symboly', keywords: ['hněv', 'žíla'] },
    { char: '💮', category: 'symboly', keywords: ['kytka', 'výborně'] },
    { char: '🔞', category: 'symboly', keywords: ['18', 'zákaz', 'dospělí'] },
    { char: '♨️', category: 'symboly', keywords: ['horké', 'pára'] },
    { char: '♻️', category: 'symboly', keywords: ['recyklace', 'eko'] },
    { char: '⚜️', category: 'symboly', keywords: ['lilie'] },
    { char: '🔱', category: 'symboly', keywords: ['trojzubec', 'moře'] },
    { char: '📛', category: 'symboly', keywords: ['jmenovka', 'štítek'] },
    { char: '🌀', category: 'symboly', keywords: ['cyklón', 'tornádo'] },
    { char: '🌐', category: 'symboly', keywords: ['internet', 'svět'] },
    { char: '⬅️', category: 'symboly', keywords: ['šipka', 'vlevo'] },
    { char: '➡️', category: 'symboly', keywords: ['šipka', 'vpravo'] },
    { char: '⬆️', category: 'symboly', keywords: ['šipka', 'nahoru'] },
    { char: '⬇️', category: 'symboly', keywords: ['šipka', 'dolů'] },
    { char: '↗️', category: 'symboly', keywords: ['šipka', 'severovýchod'] },
    { char: '↘️', category: 'symboly', keywords: ['šipka', 'jihovýchod'] },
    { char: '↙️', category: 'symboly', keywords: ['šipka', 'jihozápad'] },
    { char: '↖️', category: 'symboly', keywords: ['šipka', 'severozápad'] },
    { char: '↕️', category: 'symboly', keywords: ['šipka', 'svislá'] },
    { char: '↔️', category: 'symboly', keywords: ['šipka', 'vodorovná'] },
    { char: '🔄', category: 'symboly', keywords: ['otočení', 'refresh'] },
    { char: '🔁', category: 'symboly', keywords: ['opakování'] },
    { char: '🔂', category: 'symboly', keywords: ['opakování', 'jedna'] },
    { char: '⏪', category: 'symboly', keywords: ['zpět'] },
    { char: '⏩', category: 'symboly', keywords: ['vpřed'] },
    { char: '⏫', category: 'symboly', keywords: ['nahoru', 'rychle'] },
    { char: '⏬', category: 'symboly', keywords: ['dolů', 'rychle'] },
    { char: '➕', category: 'symboly', keywords: ['plus', 'sčítání'] },
    { char: '➖', category: 'symboly', keywords: ['mínus', 'odčítání'] },
    { char: '✖️', category: 'symboly', keywords: ['krát', 'násobení'] },
    { char: '➗', category: 'symboly', keywords: ['děleno', 'dělení'] },
    { char: '🟰', category: 'symboly', keywords: ['rovná', 'se'] },
    { char: '♾️', category: 'symboly', keywords: ['nekonečno'] },
    { char: '∞', category: 'symboly', keywords: ['nekonečno'] },
    { char: '≈', category: 'symboly', keywords: ['přibližně'] },
    { char: '≠', category: 'symboly', keywords: ['nerovná', 'se'] },
    { char: '≤', category: 'symboly', keywords: ['menší', 'rovno'] },
    { char: '≥', category: 'symboly', keywords: ['větší', 'rovno'] },
    { char: '√', category: 'symboly', keywords: ['odmocnina'] },
    { char: '∑', category: 'symboly', keywords: ['suma', 'součet'] },
    { char: '∫', category: 'symboly', keywords: ['integrál'] },
    { char: 'π', category: 'symboly', keywords: ['pí'] },
    { char: '°', category: 'symboly', keywords: ['stupeň'] },
    { char: 'ℹ️', category: 'symboly', keywords: ['informace'] },
    { char: '#️⃣', category: 'symboly', keywords: ['hash', 'mřížka'] },
    { char: '*️⃣', category: 'symboly', keywords: ['hvězdička'] },
    { char: '0️⃣', category: 'symboly', keywords: ['nula'] },
    { char: '1️⃣', category: 'symboly', keywords: ['jedna'] },
    { char: '2️⃣', category: 'symboly', keywords: ['dva'] },
    { char: '3️⃣', category: 'symboly', keywords: ['tři'] },
    { char: '4️⃣', category: 'symboly', keywords: ['čtyři'] },
    { char: '5️⃣', category: 'symboly', keywords: ['pět'] },
    { char: '6️⃣', category: 'symboly', keywords: ['šest'] },
    { char: '7️⃣', category: 'symboly', keywords: ['sedm'] },
    { char: '8️⃣', category: 'symboly', keywords: ['osm'] },
    { char: '9️⃣', category: 'symboly', keywords: ['devět'] },
    { char: '🔟', category: 'symboly', keywords: ['deset'] },
    { char: '™️', category: 'symboly', keywords: ['trademark'] },
    { char: '®️', category: 'symboly', keywords: ['registered'] },
    { char: '©️', category: 'symboly', keywords: ['copyright'] },
    { char: '℗', category: 'symboly', keywords: ['copyright', 'zvukový'] },
    { char: '♈', category: 'symboly', keywords: ['beran'] },
    { char: '♉', category: 'symboly', keywords: ['býk'] },
    { char: '♊', category: 'symboly', keywords: ['blíženci'] },
    { char: '♋', category: 'symboly', keywords: ['rak'] },
    { char: '♌', category: 'symboly', keywords: ['lev'] },
    { char: '♍', category: 'symboly', keywords: ['panna'] },
    { char: '♎', category: 'symboly', keywords: ['váhy'] },
    { char: '♏', category: 'symboly', keywords: ['štír'] },
    { char: '♐', category: 'symboly', keywords: ['střelec'] },
    { char: '♑', category: 'symboly', keywords: ['kozoroh'] },
    { char: '♒', category: 'symboly', keywords: ['vodnář'] },
    { char: '♓', category: 'symboly', keywords: ['ryby'] },
    { char: '⛎', category: 'symboly', keywords: ['hadonoš'] },
    { char: '♠️', category: 'symboly', keywords: ['piky'] },
    { char: '♥️', category: 'symboly', keywords: ['srdce'] },
    { char: '♦️', category: 'symboly', keywords: ['káry'] },
    { char: '♣️', category: 'symboly', keywords: ['kříže'] },
    { char: '🃏', category: 'symboly', keywords: ['žolík'] },
    { char: '🎴', category: 'symboly', keywords: ['karty', 'japonské'] },
    { char: '🀄', category: 'symboly', keywords: ['mahjong'] },
    { char: '🎲', category: 'symboly', keywords: ['kostky'] },
    { char: '⚕️', category: 'symboly', keywords: ['lékařský', 'symbol'] },
    { char: '♿', category: 'symboly', keywords: ['vozíčkář'] },
    { char: '🚭', category: 'symboly', keywords: ['zákaz', 'kouření'] },
    { char: '📵', category: 'symboly', keywords: ['zákaz', 'mobil'] },
    { char: '☢️', category: 'symboly', keywords: ['radioaktivní'] },
    { char: '☣️', category: 'symboly', keywords: ['biologické', 'nebezpečí'] },
    { char: '⚠️', category: 'symboly', keywords: ['varování'] },
    { char: '🚸', category: 'symboly', keywords: ['děti', 'přechod'] },
    { char: '⚛️', category: 'symboly', keywords: ['atom'] },
    { char: '🕉️', category: 'symboly', keywords: ['om'] },
    { char: '✡️', category: 'symboly', keywords: ['davidova', 'hvězda'] },
    { char: '☸️', category: 'symboly', keywords: ['dharma'] },
    { char: '☯️', category: 'symboly', keywords: ['jin', 'jang'] },
    { char: '✝️', category: 'symboly', keywords: ['kříž'] },
    { char: '☦️', category: 'symboly', keywords: ['pravoslavný', 'kříž'] },
    { char: '☪️', category: 'symboly', keywords: ['islám', 'půlměsíc'] },
    { char: '☮️', category: 'symboly', keywords: ['mír'] },
    { char: '🕎', category: 'symboly', keywords: ['menora'] },
    { char: '🔯', category: 'symboly', keywords: ['hvězda', 'šesticípá'] },
    { char: '💰', category: 'symboly', keywords: ['pytel', 'peněz'] },
    { char: '💴', category: 'symboly', keywords: ['jen'] },
    { char: '💵', category: 'symboly', keywords: ['dolar'] },
    { char: '💶', category: 'symboly', keywords: ['euro'] },
    { char: '💷', category: 'symboly', keywords: ['libra'] },
    { char: '💸', category: 'symboly', keywords: ['létající', 'peníze'] },
    { char: '💳', category: 'symboly', keywords: ['kreditní', 'karta'] },
    { char: '🧾', category: 'symboly', keywords: ['účtenka'] },
    { char: '💹', category: 'symboly', keywords: ['graf', 'růst'] },

    // ==========================================
    // 3. 🐶 ZVÍŘATA A PŘÍRODA
    // ==========================================
    { char: '🐶', category: 'zvirata', keywords: ['pes', 'štěně'] },
    { char: '🐱', category: 'zvirata', keywords: ['kočka', 'kocour'] },
    { char: '🐭', category: 'zvirata', keywords: ['myš'] },
    { char: '🐹', category: 'zvirata', keywords: ['křeček'] },
    { char: '🐰', category: 'zvirata', keywords: ['králík', 'zajíc'] },
    { char: '🦊', category: 'zvirata', keywords: ['liška'] },
    { char: '🐻', category: 'zvirata', keywords: ['medvěd'] },
    { char: '🐼', category: 'zvirata', keywords: ['panda'] },
    { char: '🐨', category: 'zvirata', keywords: ['koala'] },
    { char: '🐯', category: 'zvirata', keywords: ['tygr'] },
    { char: '🦁', category: 'zvirata', keywords: ['lev'] },
    { char: '🐮', category: 'zvirata', keywords: ['kráva'] },
    { char: '🐷', category: 'zvirata', keywords: ['prase'] },
    { char: '🐸', category: 'zvirata', keywords: ['žába'] },
    { char: '🐵', category: 'zvirata', keywords: ['opice'] },
    { char: '🐔', category: 'zvirata', keywords: ['kuře', 'slepice'] },
    { char: '🐧', category: 'zvirata', keywords: ['tučňák'] },
    { char: '🐦', category: 'zvirata', keywords: ['pták'] },
    { char: '🐤', category: 'zvirata', keywords: ['kuřátko'] },
    { char: '🐣', category: 'zvirata', keywords: ['mládě', 'vylíhnutí'] },
    { char: '🐥', category: 'zvirata', keywords: ['kuřátko'] },
    { char: '🐺', category: 'zvirata', keywords: ['vlk'] },
    { char: '🐗', category: 'zvirata', keywords: ['divočák'] },
    { char: '🐴', category: 'zvirata', keywords: ['kůň'] },
    { char: '🦄', category: 'zvirata', keywords: ['jednorožec'] },
    { char: '🐝', category: 'zvirata', keywords: ['včela'] },
    { char: '🐛', category: 'zvirata', keywords: ['housenka'] },
    { char: '🦋', category: 'zvirata', keywords: ['motýl'] },
    { char: '🐌', category: 'zvirata', keywords: ['hlemýžď'] },
    { char: '🐞', category: 'zvirata', keywords: ['beruška'] },
    { char: '🐜', category: 'zvirata', keywords: ['mravenec'] },
    { char: '🦟', category: 'zvirata', keywords: ['komár'] },
    { char: '🦗', category: 'zvirata', keywords: ['cvrček'] },
    { char: '🕷️', category: 'zvirata', keywords: ['pavouk'] },
    { char: '🕸️', category: 'zvirata', keywords: ['pavučina'] },
    { char: '🦂', category: 'zvirata', keywords: ['štír'] },
    { char: '🐢', category: 'zvirata', keywords: ['želva'] },
    { char: '🐍', category: 'zvirata', keywords: ['had'] },
    { char: '🦎', category: 'zvirata', keywords: ['ještěrka'] },
    { char: '🐙', category: 'zvirata', keywords: ['chobotnice'] },
    { char: '🦑', category: 'zvirata', keywords: ['oliheň'] },
    { char: '🦐', category: 'zvirata', keywords: ['kreveta'] },
    { char: '🦞', category: 'zvirata', keywords: ['humr'] },
    { char: '🐠', category: 'zvirata', keywords: ['ryba', 'tropická'] },
    { char: '🐟', category: 'zvirata', keywords: ['ryba'] },
    { char: '🐬', category: 'zvirata', keywords: ['delfín'] },
    { char: '🐳', category: 'zvirata', keywords: ['velryba'] },
    { char: '🐋', category: 'zvirata', keywords: ['velryba'] },
    { char: '🦈', category: 'zvirata', keywords: ['žralok'] },
    { char: '🐊', category: 'zvirata', keywords: ['krokodýl'] },
    { char: '🐅', category: 'zvirata', keywords: ['tygr'] },
    { char: '🐆', category: 'zvirata', keywords: ['levhart'] },
    { char: '🦓', category: 'zvirata', keywords: ['zebra'] },
    { char: '🦍', category: 'zvirata', keywords: ['gorila'] },
    { char: '🦧', category: 'zvirata', keywords: ['orangutan'] },
    { char: '🦣', category: 'zvirata', keywords: ['mamut'] },
    { char: '🦛', category: 'zvirata', keywords: ['hroch'] },
    { char: '🦏', category: 'zvirata', keywords: ['nosorožec'] },
    { char: '🐫', category: 'zvirata', keywords: ['velbloud'] },
    { char: '🐪', category: 'zvirata', keywords: ['dromedár'] },
    { char: '🐘', category: 'zvirata', keywords: ['slon'] },
    { char: '🦒', category: 'zvirata', keywords: ['žirafa'] },
    { char: '🐃', category: 'zvirata', keywords: ['buvol'] },
    { char: '🐂', category: 'zvirata', keywords: ['býk'] },
    { char: '🐄', category: 'zvirata', keywords: ['kráva'] },
    { char: '🐎', category: 'zvirata', keywords: ['kůň'] },
    { char: '🐩', category: 'zvirata', keywords: ['pudl'] },
    { char: '🐕', category: 'zvirata', keywords: ['pes'] },
    { char: '🐈', category: 'zvirata', keywords: ['kočka'] },
    { char: '🐓', category: 'zvirata', keywords: ['kohout'] },
    { char: '🦃', category: 'zvirata', keywords: ['krocan'] },
    { char: '🐇', category: 'zvirata', keywords: ['králík'] },
    { char: '🐁', category: 'zvirata', keywords: ['myš'] },
    { char: '🐀', category: 'zvirata', keywords: ['krysa'] },
    { char: '🐿️', category: 'zvirata', keywords: ['veverka'] },
    { char: '🦔', category: 'zvirata', keywords: ['ježek'] },
    { char: '🦙', category: 'zvirata', keywords: ['lama'] },
    { char: '🦘', category: 'zvirata', keywords: ['klokan'] },
    { char: '🦕', category: 'zvirata', keywords: ['dinosaurus'] },
    { char: '🦖', category: 'zvirata', keywords: ['tyranosaurus'] },
    { char: '🐉', category: 'zvirata', keywords: ['drak'] },
    { char: '🐲', category: 'zvirata', keywords: ['drak', 'hlava'] },
    { char: '🦭', category: 'zvirata', keywords: ['lachtán'] },
    { char: '🦫', category: 'zvirata', keywords: ['bobr'] },
    { char: '🦬', category: 'zvirata', keywords: ['bizon'] },
    { char: '🦤', category: 'zvirata', keywords: ['dodo'] },
    { char: '🪶', category: 'zvirata', keywords: ['pírko'] },
    { char: '🦢', category: 'zvirata', keywords: ['labuť'] },
    { char: '🦩', category: 'zvirata', keywords: ['plameňák'] },
    { char: '🦚', category: 'zvirata', keywords: ['páv'] },
    { char: '🦜', category: 'zvirata', keywords: ['papoušek'] },
    { char: '🐡', category: 'zvirata', keywords: ['čtverzubec'] },
    { char: '🌵', category: 'zvirata', keywords: ['kaktus'] },
    { char: '🎄', category: 'zvirata', keywords: ['vánoční', 'stromek'] },
    { char: '🌲', category: 'zvirata', keywords: ['strom', 'jehličnan'] },
    { char: '🌳', category: 'zvirata', keywords: ['listnatý', 'strom'] },
    { char: '🌴', category: 'zvirata', keywords: ['palma'] },
    { char: '🌱', category: 'zvirata', keywords: ['semenáček'] },
    { char: '🌿', category: 'zvirata', keywords: ['bylina'] },
    { char: '☘️', category: 'zvirata', keywords: ['jetel'] },
    { char: '🍀', category: 'zvirata', keywords: ['čtyřlístek'] },
    { char: '🍁', category: 'zvirata', keywords: ['javorový', 'list'] },
    { char: '🍂', category: 'zvirata', keywords: ['podzimní', 'listí'] },
    { char: '🍃', category: 'zvirata', keywords: ['listí', 've větru'] },
    { char: '🪹', category: 'zvirata', keywords: ['dutina', 'stromu'] },
    { char: '🪺', category: 'zvirata', keywords: ['hnízdo'] },
    { char: '🪻', category: 'zvirata', keywords: ['hyacint'] },
    { char: '🌻', category: 'zvirata', keywords: ['slunečnice'] },
    { char: '🌼', category: 'zvirata', keywords: ['kytka'] },
    { char: '🌷', category: 'zvirata', keywords: ['tulipán'] },
    { char: '🌹', category: 'zvirata', keywords: ['růže'] },
    { char: '🥀', category: 'zvirata', keywords: ['uvadlá', 'kytka'] },
    { char: '🌸', category: 'zvirata', keywords: ['třešňový', 'květ'] },
    { char: '💐', category: 'zvirata', keywords: ['kytice'] },

    // ==========================================
    // 4. 🍕 JÍDLO A NÁPOJE
    // ==========================================
    { char: '🍎', category: 'jidlo', keywords: ['jablko'] },
    { char: '🍐', category: 'jidlo', keywords: ['hruška'] },
    { char: '🍊', category: 'jidlo', keywords: ['pomeranč'] },
    { char: '🍋', category: 'jidlo', keywords: ['citrón'] },
    { char: '🍌', category: 'jidlo', keywords: ['banán'] },
    { char: '🍉', category: 'jidlo', keywords: ['meloun'] },
    { char: '🍇', category: 'jidlo', keywords: ['hrozny'] },
    { char: '🍓', category: 'jidlo', keywords: ['jahoda'] },
    { char: '🫐', category: 'jidlo', keywords: ['borůvka'] },
    { char: '🍒', category: 'jidlo', keywords: ['třešeň'] },
    { char: '🥝', category: 'jidlo', keywords: ['kiwi'] },
    { char: '🥑', category: 'jidlo', keywords: ['avokádo'] },
    { char: '🥦', category: 'jidlo', keywords: ['brokolice'] },
    { char: '🥬', category: 'jidlo', keywords: ['zelí'] },
    { char: '🍅', category: 'jidlo', keywords: ['rajče'] },
    { char: '🌽', category: 'jidlo', keywords: ['kukuřice'] },
    { char: '🥕', category: 'jidlo', keywords: ['mrkev'] },
    { char: '🍕', category: 'jidlo', keywords: ['pizza'] },
    { char: '🍔', category: 'jidlo', keywords: ['hamburger'] },
    { char: '🍟', category: 'jidlo', keywords: ['hranolky'] },
    { char: '🌭', category: 'jidlo', keywords: ['párek'] },
    { char: '🥪', category: 'jidlo', keywords: ['sendvič'] },
    { char: '🌮', category: 'jidlo', keywords: ['taco'] },
    { char: '🌯', category: 'jidlo', keywords: ['burrito'] },
    { char: '🥙', category: 'jidlo', keywords: ['gyros'] },
    { char: '🧆', category: 'jidlo', keywords: ['falafel'] },
    { char: '🥚', category: 'jidlo', keywords: ['vajíčko'] },
    { char: '🍳', category: 'jidlo', keywords: ['smažení'] },
    { char: '🥘', category: 'jidlo', keywords: ['pánev'] },
    { char: '🍲', category: 'jidlo', keywords: ['hrnec', 'polévka'] },
    { char: '🥣', category: 'jidlo', keywords: ['mísa'] },
    { char: '🥗', category: 'jidlo', keywords: ['salát'] },
    { char: '🍿', category: 'jidlo', keywords: ['popcorn'] },
    { char: '🧂', category: 'jidlo', keywords: ['sůl'] },
    { char: '🥨', category: 'jidlo', keywords: ['preclík'] },
    { char: '🥖', category: 'jidlo', keywords: ['bageta'] },
    { char: '🍞', category: 'jidlo', keywords: ['chléb'] },
    { char: '🥐', category: 'jidlo', keywords: ['croissant'] },
    { char: '🥞', category: 'jidlo', keywords: ['palačinka'] },
    { char: '🧀', category: 'jidlo', keywords: ['sýr'] },
    { char: '🍖', category: 'jidlo', keywords: ['maso'] },
    { char: '🍗', category: 'jidlo', keywords: ['kuře'] },
    { char: '🥩', category: 'jidlo', keywords: ['steak'] },
    { char: '🥓', category: 'jidlo', keywords: ['slanina'] },
    { char: '🍣', category: 'jidlo', keywords: ['sushi'] },
    { char: '🍱', category: 'jidlo', keywords: ['bentó'] },
    { char: '🥟', category: 'jidlo', keywords: ['knedlík'] },
    { char: '🍦', category: 'jidlo', keywords: ['zmrzlina'] },
    { char: '🍧', category: 'jidlo', keywords: ['ledový'] },
    { char: '🍨', category: 'jidlo', keywords: ['zmrzlina'] },
    { char: '🍩', category: 'jidlo', keywords: ['donut'] },
    { char: '🍪', category: 'jidlo', keywords: ['sušenka'] },
    { char: '🎂', category: 'jidlo', keywords: ['dort', 'narozeniny'] },
    { char: '🍰', category: 'jidlo', keywords: ['dort'] },
    { char: '🧁', category: 'jidlo', keywords: ['košíček'] },
    { char: '🥧', category: 'jidlo', keywords: ['koláč'] },
    { char: '🍫', category: 'jidlo', keywords: ['čokoláda'] },
    { char: '🍬', category: 'jidlo', keywords: ['bonbón'] },
    { char: '🍭', category: 'jidlo', keywords: ['lízátko'] },
    { char: '🍮', category: 'jidlo', keywords: ['pudink'] },
    { char: '🍯', category: 'jidlo', keywords: ['med'] },
    { char: '☕', category: 'jidlo', keywords: ['káva'] },
    { char: '🍵', category: 'jidlo', keywords: ['čaj'] },
    { char: '🥤', category: 'jidlo', keywords: ['nápoj'] },
    { char: '🧃', category: 'jidlo', keywords: ['džus'] },
    { char: '🥛', category: 'jidlo', keywords: ['mléko'] },
    { char: '🍺', category: 'jidlo', keywords: ['pivo'] },
    { char: '🍻', category: 'jidlo', keywords: ['piva'] },
    { char: '🥂', category: 'jidlo', keywords: ['přípitek'] },
    { char: '🍷', category: 'jidlo', keywords: ['víno'] },
    { char: '🥃', category: 'jidlo', keywords: ['whisky'] },
    { char: '🥄', category: 'jidlo', keywords: ['lžíce'] },
    { char: '🔪', category: 'jidlo', keywords: ['nůž'] },
    { char: '🏺', category: 'jidlo', keywords: ['amfora'] },
    { char: '🥥', category: 'jidlo', keywords: ['kokos'] },
    { char: '🥭', category: 'jidlo', keywords: ['mango'] },
    { char: '🍍', category: 'jidlo', keywords: ['ananas'] },
    { char: '🥔', category: 'jidlo', keywords: ['brambora'] },
    { char: '🍠', category: 'jidlo', keywords: ['batát'] },
    { char: '🥒', category: 'jidlo', keywords: ['okurka'] },
    { char: '🫛', category: 'jidlo', keywords: ['hrášek'] },
    { char: '🧄', category: 'jidlo', keywords: ['česnek'] },
    { char: '🧅', category: 'jidlo', keywords: ['cibule'] },
    { char: '🥜', category: 'jidlo', keywords: ['arašíd'] },
    { char: '🌰', category: 'jidlo', keywords: ['kaštan'] },
    { char: '🫚', category: 'jidlo', keywords: ['zázvor'] },
    { char: '🫕', category: 'jidlo', keywords: ['fondue'] },
    { char: '🥮', category: 'jidlo', keywords: ['měsíční', 'koláček'] },
    { char: '🍘', category: 'jidlo', keywords: ['rýžový', 'krekr'] },
    { char: '🍙', category: 'jidlo', keywords: ['rýžová', 'koule'] },
    { char: '🍚', category: 'jidlo', keywords: ['rýže'] },
    { char: '🍛', category: 'jidlo', keywords: ['kari'] },
    { char: '🍜', category: 'jidlo', keywords: ['nudle'] },
    { char: '🍝', category: 'jidlo', keywords: ['těstoviny'] },
    { char: '🍢', category: 'jidlo', keywords: ['kebab'] },
    { char: '🍡', category: 'jidlo', keywords: ['dango'] },
    { char: '🍥', category: 'jidlo', keywords: ['narutomaki'] },
    { char: '🥠', category: 'jidlo', keywords: ['fortune', 'cookie'] },

    // ==========================================
    // 5. ⚽ SPORT A AKTIVITY
    // ==========================================
    { char: '⚽', category: 'sport', keywords: ['fotbal', 'míč'] },
    { char: '🏀', category: 'sport', keywords: ['basketball'] },
    { char: '🏈', category: 'sport', keywords: ['americký', 'fotbal'] },
    { char: '⚾', category: 'sport', keywords: ['baseball'] },
    { char: '🥎', category: 'sport', keywords: ['softball'] },
    { char: '🎾', category: 'sport', keywords: ['tenis'] },
    { char: '🏐', category: 'sport', keywords: ['volejbal'] },
    { char: '🏉', category: 'sport', keywords: ['ragby'] },
    { char: '🥏', category: 'sport', keywords: ['létající', 'talíř'] },
    { char: '🎱', category: 'sport', keywords: ['kulečník'] },
    { char: '🪀', category: 'sport', keywords: ['yo-yo'] },
    { char: '🏓', category: 'sport', keywords: ['pingpong'] },
    { char: '🏸', category: 'sport', keywords: ['badminton'] },
    { char: '🏒', category: 'sport', keywords: ['hokej'] },
    { char: '🏑', category: 'sport', keywords: ['pozemní', 'hokej'] },
    { char: '🥍', category: 'sport', keywords: ['lakros'] },
    { char: '🏏', category: 'sport', keywords: ['kriket'] },
    { char: '🥅', category: 'sport', keywords: ['brána'] },
    { char: '⛳', category: 'sport', keywords: ['golf'] },
    { char: '🏹', category: 'sport', keywords: ['luk', 'šíp'] },
    { char: '🎣', category: 'sport', keywords: ['rybaření'] },
    { char: '🥊', category: 'sport', keywords: ['box'] },
    { char: '🥋', category: 'sport', keywords: ['karate'] },
    { char: '🎽', category: 'sport', keywords: ['běh'] },
    { char: '🛹', category: 'sport', keywords: ['skateboard'] },
    { char: '🛼', category: 'sport', keywords: ['brusle'] },
    { char: '🚴', category: 'sport', keywords: ['kolo'] },
    { char: '🏋️', category: 'sport', keywords: ['posilování'] },
    { char: '🤸', category: 'sport', keywords: ['akrobacie'] },
    { char: '🤼', category: 'sport', keywords: ['zápas'] },
    { char: '🤽', category: 'sport', keywords: ['vodní', 'pólo'] },
    { char: '🤾', category: 'sport', keywords: ['házená'] },
    { char: '🥌', category: 'sport', keywords: ['curling'] },
    { char: '🤿', category: 'sport', keywords: ['potápění'] },
    { char: '🪂', category: 'sport', keywords: ['padák'] },
    { char: '🏅', category: 'sport', keywords: ['medaile'] },
    { char: '🥇', category: 'sport', keywords: ['zlato'] },
    { char: '🥈', category: 'sport', keywords: ['stříbro'] },
    { char: '🥉', category: 'sport', keywords: ['bronz'] },
    { char: '🏆', category: 'sport', keywords: ['trofej'] },
    { char: '🏵️', category: 'sport', keywords: ['růžice'] },
    { char: '🎖️', category: 'sport', keywords: ['medaile', 'vojenská'] },
    { char: '🪁', category: 'sport', keywords: ['drak'] },
    { char: '🛝', category: 'sport', keywords: ['skluzavka'] },
    { char: '🛴', category: 'sport', keywords: ['koloběžka'] },
    { char: '⛸️', category: 'sport', keywords: ['brusle', 'lední'] },
    { char: '🎿', category: 'sport', keywords: ['lyže'] },
    { char: '🏂', category: 'sport', keywords: ['snowboard'] },
    { char: '🏄', category: 'sport', keywords: ['surfování'] },
    { char: '🪢', category: 'sport', keywords: ['uzel'] },

    // ==========================================
    // 6. 🚗 CESTOVÁNÍ, DOPRAVA A MÍSTA
    // ==========================================
    { char: '🚗', category: 'doprava', keywords: ['auto'] },
    { char: '🚕', category: 'doprava', keywords: ['taxi'] },
    { char: '🚙', category: 'doprava', keywords: ['SUV'] },
    { char: '🚌', category: 'doprava', keywords: ['bus'] },
    { char: '🚎', category: 'doprava', keywords: ['trolejbus'] },
    { char: '🏎️', category: 'doprava', keywords: ['závodní', 'auto'] },
    { char: '🚓', category: 'doprava', keywords: ['policejní'] },
    { char: '🚑', category: 'doprava', keywords: ['sanitka'] },
    { char: '🚒', category: 'doprava', keywords: ['hasiči'] },
    { char: '🚐', category: 'doprava', keywords: ['dodávka'] },
    { char: '🚚', category: 'doprava', keywords: ['nákladní'] },
    { char: '🚛', category: 'doprava', keywords: ['nákladní'] },
    { char: '🚜', category: 'doprava', keywords: ['traktor'] },
    { char: '🏍️', category: 'doprava', keywords: ['motorka'] },
    { char: '🛵', category: 'doprava', keywords: ['skútr'] },
    { char: '🚲', category: 'doprava', keywords: ['kolo'] },
    { char: '🚨', category: 'doprava', keywords: ['maják'] },
    { char: '🚔', category: 'doprava', keywords: ['police'] },
    { char: '🚍', category: 'doprava', keywords: ['bus'] },
    { char: '🚘', category: 'doprava', keywords: ['auto'] },
    { char: '🚖', category: 'doprava', keywords: ['taxi'] },
    { char: '✈️', category: 'doprava', keywords: ['letadlo'] },
    { char: '🛩️', category: 'doprava', keywords: ['malé', 'letadlo'] },
    { char: '🛫', category: 'doprava', keywords: ['odlet'] },
    { char: '🛬', category: 'doprava', keywords: ['přílet'] },
    { char: '🚁', category: 'doprava', keywords: ['helikoptéra'] },
    { char: '🚟', category: 'doprava', keywords: ['visutá', 'dráha'] },
    { char: '🚠', category: 'doprava', keywords: ['lanovka'] },
    { char: '🚡', category: 'doprava', keywords: ['lanovka'] },
    { char: '🚂', category: 'doprava', keywords: ['vlak'] },
    { char: '🚆', category: 'doprava', keywords: ['vlak'] },
    { char: '🚇', category: 'doprava', keywords: ['metro'] },
    { char: '🚉', category: 'doprava', keywords: ['nádraží'] },
    { char: '🚊', category: 'doprava', keywords: ['tramvaj'] },
    { char: '🚝', category: 'doprava', keywords: ['monorail'] },
    { char: '🚞', category: 'doprava', keywords: ['horská', 'dráha'] },
    { char: '🚋', category: 'doprava', keywords: ['tramvaj'] },
    { char: '🚤', category: 'doprava', keywords: ['loď'] },
    { char: '🛥️', category: 'doprava', keywords: ['motorová', 'loď'] },
    { char: '🛳️', category: 'doprava', keywords: ['lod'] },
    { char: '⛴️', category: 'doprava', keywords: ['ferry'] },
    { char: '🚢', category: 'doprava', keywords: ['loď'] },
    { char: '🛶', category: 'doprava', keywords: ['kánoe'] },
    { char: '🚀', category: 'doprava', keywords: ['raketa'] },
    { char: '🛸', category: 'doprava', keywords: ['ufo'] },
    { char: '🛻', category: 'doprava', keywords: ['pickup'] },
    { char: '🛺', category: 'doprava', keywords: ['tuk-tuk'] },
    { char: '🛞', category: 'doprava', keywords: ['kolo', 'pneumatika'] },
    { char: '⛵', category: 'doprava', keywords: ['plachetnice'] },
    { char: '🏠', category: 'doprava', keywords: ['dům'] },
    { char: '🏡', category: 'doprava', keywords: ['dům', 'zahrada'] },
    { char: '🏢', category: 'doprava', keywords: ['kancelář'] },
    { char: '🏣', category: 'doprava', keywords: ['pošta'] },
    { char: '🏤', category: 'doprava', keywords: ['pošta'] },
    { char: '🏥', category: 'doprava', keywords: ['nemocnice'] },
    { char: '🏦', category: 'doprava', keywords: ['banka'] },
    { char: '🏨', category: 'doprava', keywords: ['hotel'] },
    { char: '🏩', category: 'doprava', keywords: ['love', 'hotel'] },
    { char: '🏪', category: 'doprava', keywords: ['obchod'] },
    { char: '🏫', category: 'doprava', keywords: ['škola'] },
    { char: '🏬', category: 'doprava', keywords: ['obchodní', 'dům'] },
    { char: '🏭', category: 'doprava', keywords: ['továrna'] },
    { char: '🏯', category: 'doprava', keywords: ['hrad', 'japonský'] },
    { char: '🏰', category: 'doprava', keywords: ['hrad'] },
    { char: '💒', category: 'doprava', keywords: ['svatba'] },
    { char: '🗼', category: 'doprava', keywords: ['eiffelovka'] },
    { char: '🗽', category: 'doprava', keywords: ['socha', 'svobody'] },
    { char: '⛪', category: 'doprava', keywords: ['kostel'] },
    { char: '🕌', category: 'doprava', keywords: ['mešita'] },
    { char: '🛕', category: 'doprava', keywords: ['chrám'] },
    { char: '🕍', category: 'doprava', keywords: ['synagoga'] },
    { char: '⛩️', category: 'doprava', keywords: ['brána', 'japonská'] },
    { char: '🕋', category: 'doprava', keywords: ['kaaba'] },
    { char: '⛲', category: 'doprava', keywords: ['fontána'] },
    { char: '⛺', category: 'doprava', keywords: ['stan'] },
    { char: '🌁', category: 'doprava', keywords: ['mlha'] },
    { char: '🌃', category: 'doprava', keywords: ['noc', 'město'] },
    { char: '🌄', category: 'doprava', keywords: ['východ', 'slunce'] },
    { char: '🌅', category: 'doprava', keywords: ['východ', 'slunce'] },
    { char: '🌆', category: 'doprava', keywords: ['soumrak'] },
    { char: '🌇', category: 'doprava', keywords: ['západ', 'slunce'] },
    { char: '🌉', category: 'doprava', keywords: ['most'] },
    { char: '🗺️', category: 'doprava', keywords: ['mapa'] },
    { char: '🗾', category: 'doprava', keywords: ['japonsko'] },
    { char: '🧭', category: 'doprava', keywords: ['kompas'] },
    { char: '🌍', category: 'doprava', keywords: ['země'] },
    { char: '🌎', category: 'doprava', keywords: ['země', 'amerika'] },
    { char: '🌏', category: 'doprava', keywords: ['země', 'asie'] },
    { char: '⛰️', category: 'doprava', keywords: ['hora'] },
    { char: '🏔️', category: 'doprava', keywords: ['hora', 'sníh'] },
    { char: '🌋', category: 'doprava', keywords: ['sopka'] },
    { char: '🗻', category: 'doprava', keywords: ['fuji'] },
    { char: '🏕️', category: 'doprava', keywords: ['kemp'] },
    { char: '🏖️', category: 'doprava', keywords: ['pláž'] },
    { char: '🏜️', category: 'doprava', keywords: ['poušť'] },
    { char: '🏝️', category: 'doprava', keywords: ['ostrov'] },
    { char: '🏞️', category: 'doprava', keywords: ['národní', 'park'] },
    { char: '🏟️', category: 'doprava', keywords: ['stadion'] },
    { char: '🏛️', category: 'doprava', keywords: ['klasická', 'budova'] },
    { char: '🏗️', category: 'doprava', keywords: ['stavba'] },
    { char: '🧱', category: 'doprava', keywords: ['cihla'] },
    { char: '🪨', category: 'doprava', keywords: ['kámen'] },
    { char: '🪵', category: 'doprava', keywords: ['dřevo'] },
    { char: '🛖', category: 'doprava', keywords: ['chýše'] },
    { char: '☀️', category: 'doprava', keywords: ['slunce'] },
    { char: '☁️', category: 'doprava', keywords: ['mrak'] },
    { char: '⛅', category: 'doprava', keywords: ['slunce', 'mrak'] },
    { char: '⛈️', category: 'doprava', keywords: ['bouřka'] },
    { char: '🌤️', category: 'doprava', keywords: ['slunce', 'mrak'] },
    { char: '🌥️', category: 'doprava', keywords: ['zataženo'] },
    { char: '🌦️', category: 'doprava', keywords: ['slunce', 'déšť'] },
    { char: '🌧️', category: 'doprava', keywords: ['déšť'] },
    { char: '🌨️', category: 'doprava', keywords: ['sníh'] },
    { char: '🌩️', category: 'doprava', keywords: ['blesk'] },
    { char: '🌪️', category: 'doprava', keywords: ['tornádo'] },
    { char: '🌫️', category: 'doprava', keywords: ['mlha'] },
    { char: '🌬️', category: 'doprava', keywords: ['vítr'] },
    { char: '🌈', category: 'doprava', keywords: ['duha'] },
    { char: '☔', category: 'doprava', keywords: ['deštník'] },
    { char: '⚡', category: 'doprava', keywords: ['blesk'] },
    { char: '❄️', category: 'doprava', keywords: ['sněhová', 'vločka'] },
    { char: '☃️', category: 'doprava', keywords: ['sněhulák'] },
    { char: '⛄', category: 'doprava', keywords: ['sněhulák'] },
    { char: '☄️', category: 'doprava', keywords: ['kometa'] },
    { char: '🌠', category: 'doprava', keywords: ['padající', 'hvězda'] },
    { char: '🌡️', category: 'doprava', keywords: ['teploměr'] },

    // ==========================================
    // 7. 📱 PŘEDMĚTY
    // ==========================================
    { char: '📱', category: 'predmety', keywords: ['mobil'] },
    { char: '📲', category: 'predmety', keywords: ['mobil', 'volání'] },
    { char: '💻', category: 'predmety', keywords: ['počítač'] },
    { char: '🖥️', category: 'predmety', keywords: ['monitor'] },
    { char: '🖨️', category: 'predmety', keywords: ['tiskárna'] },
    { char: '⌨️', category: 'predmety', keywords: ['klávesnice'] },
    { char: '🖱️', category: 'predmety', keywords: ['myš'] },
    { char: '🖲️', category: 'predmety', keywords: ['trackball'] },
    { char: '💽', category: 'predmety', keywords: ['disk'] },
    { char: '💾', category: 'predmety', keywords: ['disketa'] },
    { char: '💿', category: 'predmety', keywords: ['cd'] },
    { char: '📀', category: 'predmety', keywords: ['dvd'] },
    { char: '📷', category: 'predmety', keywords: ['fotoaparát'] },
    { char: '📸', category: 'predmety', keywords: ['fotoaparát'] },
    { char: '📹', category: 'predmety', keywords: ['kamera'] },
    { char: '🎥', category: 'predmety', keywords: ['kamera'] },
    { char: '📽️', category: 'predmety', keywords: ['projektor'] },
    { char: '🎬', category: 'predmety', keywords: ['film'] },
    { char: '📺', category: 'predmety', keywords: ['televize'] },
    { char: '📻', category: 'predmety', keywords: ['rádio'] },
    { char: '🎙️', category: 'predmety', keywords: ['mikrofon'] },
    { char: '🎚️', category: 'predmety', keywords: ['ovladač'] },
    { char: '🎛️', category: 'predmety', keywords: ['ovládací', 'panel'] },
    { char: '🎧', category: 'predmety', keywords: ['sluchátka'] },
    { char: '📞', category: 'predmety', keywords: ['telefon'] },
    { char: '☎️', category: 'predmety', keywords: ['telefon'] },
    { char: '📟', category: 'predmety', keywords: ['pager'] },
    { char: '📠', category: 'predmety', keywords: ['fax'] },
    { char: '🔋', category: 'predmety', keywords: ['baterie'] },
    { char: '🪫', category: 'predmety', keywords: ['vybitá', 'baterie'] },
    { char: '🔌', category: 'predmety', keywords: ['zástrčka'] },
    { char: '💡', category: 'predmety', keywords: ['žárovka', 'nápad'] },
    { char: '🔦', category: 'predmety', keywords: ['baterka'] },
    { char: '🕯️', category: 'predmety', keywords: ['svíčka'] },
    { char: '🪔', category: 'predmety', keywords: ['lampa'] },
    { char: '📡', category: 'predmety', keywords: ['satelit'] },
    { char: '💎', category: 'predmety', keywords: ['drahokam'] },
    { char: '🔮', category: 'predmety', keywords: ['křišťál'] },
    { char: '🎨', category: 'predmety', keywords: ['umění'] },
    { char: '🖌️', category: 'predmety', keywords: ['štětec'] },
    { char: '🖍️', category: 'predmety', keywords: ['pastelka'] },
    { char: '✂️', category: 'predmety', keywords: ['nůžky'] },
    { char: '🧵', category: 'predmety', keywords: ['nit'] },
    { char: '🧶', category: 'predmety', keywords: ['vlna'] },
    { char: '🔒', category: 'predmety', keywords: ['zámek'] },
    { char: '🔓', category: 'predmety', keywords: ['odemčeno'] },
    { char: '🔐', category: 'predmety', keywords: ['zámek', 'klíč'] },
    { char: '🔑', category: 'predmety', keywords: ['klíč'] },
    { char: '🔨', category: 'predmety', keywords: ['kladivo'] },
    { char: '🪓', category: 'predmety', keywords: ['sekera'] },
    { char: '⛏️', category: 'predmety', keywords: ['krumpáč'] },
    { char: '🔧', category: 'predmety', keywords: ['klíč'] },
    { char: '🔩', category: 'predmety', keywords: ['šroub'] },
    { char: '⚙️', category: 'predmety', keywords: ['ozubené', 'kolo'] },
    { char: '🗜️', category: 'predmety', keywords: ['svěrák'] },
    { char: '🔫', category: 'predmety', keywords: ['zbraň'] },
    { char: '💣', category: 'predmety', keywords: ['bomba'] },
    { char: '🧨', category: 'predmety', keywords: ['petarda'] },
    { char: '🪚', category: 'predmety', keywords: ['pila'] },
    { char: '⚗️', category: 'predmety', keywords: ['baňka'] },
    { char: '🧪', category: 'predmety', keywords: ['zkumavka'] },
    { char: '🧫', category: 'predmety', keywords: ['petriho', 'miska'] },
    { char: '🔬', category: 'predmety', keywords: ['mikroskop'] },
    { char: '🔭', category: 'predmety', keywords: ['dalekohled'] },
    { char: '💉', category: 'predmety', keywords: ['injekce'] },
    { char: '🩸', category: 'predmety', keywords: ['krev'] },
    { char: '💊', category: 'predmety', keywords: ['pilulka'] },
    { char: '🩹', category: 'predmety', keywords: ['náplast'] },
    { char: '🩺', category: 'predmety', keywords: ['stetoskop'] },
    { char: '🩻', category: 'predmety', keywords: ['rentgen'] },
    { char: '🩼', category: 'predmety', keywords: ['berle'] },
    { char: '🚪', category: 'predmety', keywords: ['dveře'] },
    { char: '🪞', category: 'predmety', keywords: ['zrcadlo'] },
    { char: '🪟', category: 'predmety', keywords: ['okno'] },
    { char: '🛏️', category: 'predmety', keywords: ['postel'] },
    { char: '🛋️', category: 'predmety', keywords: ['gauč'] },
    { char: '🚽', category: 'predmety', keywords: ['záchod'] },
    { char: '🚿', category: 'predmety', keywords: ['sprcha'] },
    { char: '🛁', category: 'predmety', keywords: ['vana'] },
    { char: '🪠', category: 'predmety', keywords: ['zvon'] },
    { char: '🧹', category: 'predmety', keywords: ['koště'] },
    { char: '🧺', category: 'predmety', keywords: ['koš'] },
    { char: '🧻', category: 'predmety', keywords: ['toaletní', 'papír'] },
    { char: '🧼', category: 'predmety', keywords: ['mýdlo'] },
    { char: '🧽', category: 'predmety', keywords: ['houba'] },
    { char: '🧯', category: 'predmety', keywords: ['hasicí'] },
    { char: '🛒', category: 'predmety', keywords: ['nákupní', 'košík'] },
    { char: '🚬', category: 'predmety', keywords: ['cigareta'] },
    { char: '⚰️', category: 'predmety', keywords: ['rakev'] },
    { char: '⚱️', category: 'predmety', keywords: ['urna'] },
    { char: '🗿', category: 'predmety', keywords: ['moai'] },
    { char: '🪆', category: 'predmety', keywords: ['matrjoška'] },
    { char: '⌚', category: 'predmety', keywords: ['hodinky'] },
    { char: '⏰', category: 'predmety', keywords: ['budík'] },
    { char: '⏲️', category: 'predmety', keywords: ['časovač'] },
    { char: '⏱️', category: 'predmety', keywords: ['stopky'] },
    { char: '⌛', category: 'predmety', keywords: ['přesýpací', 'hodiny'] },
    { char: '⏳', category: 'predmety', keywords: ['přesýpací'] },
    { char: '📅', category: 'predmety', keywords: ['kalendář'] },
    { char: '📆', category: 'predmety', keywords: ['kalendář'] },
    { char: '🗓️', category: 'predmety', keywords: ['kalendář'] },
    { char: '📋', category: 'predmety', keywords: ['klipboard'] },
    { char: '📌', category: 'predmety', keywords: ['připínáček'] },
    { char: '📍', category: 'predmety', keywords: ['špendlík'] },
    { char: '📎', category: 'predmety', keywords: ['sponka'] },
    { char: '🖇️', category: 'predmety', keywords: ['spojené', 'sponky'] },
    { char: '🔗', category: 'predmety', keywords: ['odkaz'] },
    { char: '📏', category: 'predmety', keywords: ['pravítko'] },
    { char: '📐', category: 'predmety', keywords: ['trojúhelník'] },
    { char: '✏️', category: 'predmety', keywords: ['tužka'] },
    { char: '✒️', category: 'predmety', keywords: ['pero'] },
    { char: '🖋️', category: 'predmety', keywords: ['plnící', 'pero'] },
    { char: '🖊️', category: 'predmety', keywords: ['pero'] },
    { char: '📝', category: 'predmety', keywords: ['poznámka'] },
    { char: '📒', category: 'predmety', keywords: ['sešit'] },
    { char: '📓', category: 'predmety', keywords: ['sešit'] },
    { char: '📔', category: 'predmety', keywords: ['deník'] },
    { char: '📕', category: 'predmety', keywords: ['kniha'] },
    { char: '📖', category: 'predmety', keywords: ['otevřená', 'kniha'] },
    { char: '📗', category: 'predmety', keywords: ['kniha'] },
    { char: '📘', category: 'predmety', keywords: ['kniha'] },
    { char: '📙', category: 'predmety', keywords: ['kniha'] },
    { char: '📚', category: 'predmety', keywords: ['knihy'] },
    { char: '📑', category: 'predmety', keywords: ['záložky'] },
    { char: '🔖', category: 'predmety', keywords: ['záložka'] },
    { char: '📄', category: 'predmety', keywords: ['dokument'] },
    { char: '📃', category: 'predmety', keywords: ['dokument'] },
    { char: '📜', category: 'predmety', keywords: ['svitek'] },
    { char: '📊', category: 'predmety', keywords: ['graf'] },
    { char: '📈', category: 'predmety', keywords: ['graf', 'růst'] },
    { char: '📉', category: 'predmety', keywords: ['graf', 'pokles'] },
    { char: '🧮', category: 'predmety', keywords: ['abacus'] },
    { char: '👕', category: 'predmety', keywords: ['tričko'] },
    { char: '👖', category: 'predmety', keywords: ['džíny'] },
    { char: '🧥', category: 'predmety', keywords: ['kabát'] },
    { char: '🧣', category: 'predmety', keywords: ['šála'] },
    { char: '🧤', category: 'predmety', keywords: ['rukavice'] },
    { char: '🧦', category: 'predmety', keywords: ['ponožky'] },
    { char: '👗', category: 'predmety', keywords: ['šaty'] },
    { char: '👘', category: 'predmety', keywords: ['kimono'] },
    { char: '🥻', category: 'predmety', keywords: ['sárí'] },
    { char: '🩱', category: 'predmety', keywords: ['plavky'] },
    { char: '🩲', category: 'predmety', keywords: ['trenýrky'] },
    { char: '🩳', category: 'predmety', keywords: ['šortky'] },
    { char: '👙', category: 'predmety', keywords: ['bikiny'] },
    { char: '👚', category: 'predmety', keywords: ['oblečení'] },
    { char: '👛', category: 'predmety', keywords: ['peněženka'] },
    { char: '👜', category: 'predmety', keywords: ['kabelka'] },
    { char: '👝', category: 'predmety', keywords: ['taštička'] },
    { char: '🛍️', category: 'predmety', keywords: ['nákupní', 'tašky'] },
    { char: '🎒', category: 'predmety', keywords: ['batoh'] },
    { char: '👞', category: 'predmety', keywords: ['bota'] },
    { char: '👟', category: 'predmety', keywords: ['sportovní', 'bota'] },
    { char: '🥾', category: 'predmety', keywords: ['trekingová', 'bota'] },
    { char: '🥿', category: 'predmety', keywords: ['balerína'] },
    { char: '👠', category: 'predmety', keywords: ['lodičky'] },
    { char: '👡', category: 'predmety', keywords: ['sandály'] },
    { char: '🩰', category: 'predmety', keywords: ['baletní'] },
    { char: '👢', category: 'predmety', keywords: ['kozačky'] },
    { char: '👑', category: 'predmety', keywords: ['koruna'] },
    { char: '👒', category: 'predmety', keywords: ['klobouk'] },
    { char: '🎩', category: 'predmety', keywords: ['cylindr'] },
    { char: '🎓', category: 'predmety', keywords: ['absolventský'] },
    { char: '🧢', category: 'predmety', keywords: ['baseballová', 'čepice'] },
    { char: '🪖', category: 'predmety', keywords: ['vojenská', 'helma'] },
    { char: '⛑️', category: 'predmety', keywords: ['záchranářská', 'helma'] },
    { char: '💄', category: 'predmety', keywords: ['rtěnka'] },
    { char: '💍', category: 'predmety', keywords: ['prsten'] },
    { char: '🎺', category: 'predmety', keywords: ['trubka'] },
    { char: '🎷', category: 'predmety', keywords: ['saxofon'] },
    { char: '🎸', category: 'predmety', keywords: ['kytara'] },
    { char: '🎹', category: 'predmety', keywords: ['klavír'] },
    { char: '🎻', category: 'predmety', keywords: ['housle'] },
    { char: '🥁', category: 'predmety', keywords: ['bicí'] },
    { char: '🪈', category: 'predmety', keywords: ['flétna'] },
    { char: '🪭', category: 'predmety', keywords: ['vějíř'] },
    { char: '🪮', category: 'predmety', keywords: ['hřeben'] },
    { char: '🪤', category: 'predmety', keywords: ['past'] },
    { char: '🪥', category: 'predmety', keywords: ['kartáček'] },
    { char: '🪦', category: 'predmety', keywords: ['náhrobek'] },
    { char: '🪧', category: 'predmety', keywords: ['plakát'] },
    { char: '🪬', category: 'predmety', keywords: ['hamsa'] },
    { char: '🪩', category: 'predmety', keywords: ['disco', 'koule'] },
    { char: '🪘', category: 'predmety', keywords: ['buben'] },
    { char: '🪕', category: 'predmety', keywords: ['banjo'] },
    { char: '🪗', category: 'predmety', keywords: ['akordeon'] },
    { char: '🪣', category: 'predmety', keywords: ['kbelík'] },

    // ==========================================
    // 8. 🏳️ VLAJKY
    // ==========================================
    { char: '🏳️‍🌈', category: 'flagy', keywords: ['duha', 'pride', 'lgbt'] },
    { char: '🏳️‍⚧️', category: 'flagy', keywords: ['transgender'] },
    { char: '🇨🇿', category: 'flagy', keywords: ['česko', 'czech'] },
    { char: '🇸🇰', category: 'flagy', keywords: ['slovensko'] },
    { char: '🇺🇸', category: 'flagy', keywords: ['usa', 'amerika'] },
    { char: '🇬🇧', category: 'flagy', keywords: ['británie', 'uk'] },
    { char: '🇩🇪', category: 'flagy', keywords: ['německo'] },
    { char: '🇫🇷', category: 'flagy', keywords: ['francie'] },
    { char: '🇪🇸', category: 'flagy', keywords: ['španělsko'] },
    { char: '🇮🇹', category: 'flagy', keywords: ['itálie'] },
    { char: '🇵🇱', category: 'flagy', keywords: ['polsko'] },
    { char: '🇦🇹', category: 'flagy', keywords: ['rakousko'] },
    { char: '🇭🇺', category: 'flagy', keywords: ['maďarsko'] },
    { char: '🇷🇺', category: 'flagy', keywords: ['rusko'] },
    { char: '🇨🇳', category: 'flagy', keywords: ['čína'] },
    { char: '🇯🇵', category: 'flagy', keywords: ['japonsko'] },
    { char: '🇰🇷', category: 'flagy', keywords: ['korea'] },
    { char: '🇨🇦', category: 'flagy', keywords: ['kanada'] },
    { char: '🇦🇺', category: 'flagy', keywords: ['austrálie'] },
    { char: '🇧🇷', category: 'flagy', keywords: ['brazílie'] },
    { char: '🇮🇳', category: 'flagy', keywords: ['indie'] },
    { char: '🇪🇬', category: 'flagy', keywords: ['egypt'] },
    { char: '🇿🇦', category: 'flagy', keywords: ['jižní', 'afrika'] },
    { char: '🇪🇺', category: 'flagy', keywords: ['evropa', 'eu'] },
    { char: '🇺🇳', category: 'flagy', keywords: ['osn'] },
    { char: '🇻🇦', category: 'flagy', keywords: ['vatikán'] },
    { char: '🇲🇨', category: 'flagy', keywords: ['monako'] },
    { char: '🏁', category: 'flagy', keywords: ['cílová', 'páska'] },
    { char: '🚩', category: 'flagy', keywords: ['červená', 'vlajka'] },
    { char: '🎌', category: 'flagy', keywords: ['křížené', 'vlajky'] },
    { char: '🏴', category: 'flagy', keywords: ['černá', 'vlajka'] },
    { char: '🏳️', category: 'flagy', keywords: ['bílá', 'vlajka'] },
    { char: '🏴‍☠️', category: 'flagy', keywords: ['pirát'] },
    { char: '🇦🇫', category: 'flagy', keywords: ['afghánistán'] },
    { char: '🇦🇱', category: 'flagy', keywords: ['albánie'] },
    { char: '🇩🇿', category: 'flagy', keywords: ['alžírsko'] },
    { char: '🇦🇩', category: 'flagy', keywords: ['andorra'] },
    { char: '🇦🇴', category: 'flagy', keywords: ['angola'] },
    { char: '🇦🇬', category: 'flagy', keywords: ['antigua'] },
    { char: '🇦🇷', category: 'flagy', keywords: ['argentina'] },
    { char: '🇦🇲', category: 'flagy', keywords: ['arménie'] },
    { char: '🇦🇿', category: 'flagy', keywords: ['ázerbájdžán'] },
    { char: '🇧🇸', category: 'flagy', keywords: ['bahamy'] },
    { char: '🇧🇭', category: 'flagy', keywords: ['bahrajn'] },
    { char: '🇧🇩', category: 'flagy', keywords: ['bangladéš'] },
    { char: '🇧🇧', category: 'flagy', keywords: ['barbados'] },
    { char: '🇧🇾', category: 'flagy', keywords: ['bělorusko'] },
    { char: '🇧🇪', category: 'flagy', keywords: ['belgie'] },
    { char: '🇧🇿', category: 'flagy', keywords: ['belize'] },
    { char: '🇧🇯', category: 'flagy', keywords: ['benin'] },
    { char: '🇧🇹', category: 'flagy', keywords: ['bhútán'] },
    { char: '🇧🇴', category: 'flagy', keywords: ['bolívie'] },
    { char: '🇧🇦', category: 'flagy', keywords: ['bosna'] },
    { char: '🇧🇼', category: 'flagy', keywords: ['botswana'] },
    { char: '🇧🇳', category: 'flagy', keywords: ['brunej'] },
    { char: '🇧🇬', category: 'flagy', keywords: ['bulharsko'] },
    { char: '🇧🇫', category: 'flagy', keywords: ['burkina'] },
    { char: '🇧🇮', category: 'flagy', keywords: ['burundi'] },
    { char: '🇰🇭', category: 'flagy', keywords: ['kambodža'] },
    { char: '🇨🇲', category: 'flagy', keywords: ['kamerun'] },
    { char: '🇨🇻', category: 'flagy', keywords: ['kapverdy'] },
    { char: '🇨🇫', category: 'flagy', keywords: ['středoafrická'] },
    { char: '🇹🇩', category: 'flagy', keywords: ['čad'] },
    { char: '🇨🇱', category: 'flagy', keywords: ['chile'] },
    { char: '🇨🇴', category: 'flagy', keywords: ['kolumbie'] },
    { char: '🇰🇲', category: 'flagy', keywords: ['komory'] },
    { char: '🇨🇬', category: 'flagy', keywords: ['kongo'] },
    { char: '🇨🇩', category: 'flagy', keywords: ['dr', 'kongo'] },
    { char: '🇨🇷', category: 'flagy', keywords: ['kostarika'] },
    { char: '🇨🇮', category: 'flagy', keywords: ['pobřeží', 'slonoviny'] },
    { char: '🇭🇷', category: 'flagy', keywords: ['chorvatsko'] },
    { char: '🇨🇺', category: 'flagy', keywords: ['kuba'] },
    { char: '🇨🇾', category: 'flagy', keywords: ['kypr'] },
    { char: '🇩🇰', category: 'flagy', keywords: ['dánsko'] },
    { char: '🇩🇯', category: 'flagy', keywords: ['džibutsko'] },
    { char: '🇩🇲', category: 'flagy', keywords: ['dominika'] },
    { char: '🇩🇴', category: 'flagy', keywords: ['dominikánská'] },
    { char: '🇪🇨', category: 'flagy', keywords: ['ekvádor'] },
    { char: '🇬🇶', category: 'flagy', keywords: ['rovníková', 'guinea'] },
    { char: '🇪🇷', category: 'flagy', keywords: ['eritrea'] },
    { char: '🇪🇪', category: 'flagy', keywords: ['estonsko'] },
    { char: '🇸🇿', category: 'flagy', keywords: ['svazijsko'] },
    { char: '🇪🇹', category: 'flagy', keywords: ['etiopie'] },
    { char: '🇫🇯', category: 'flagy', keywords: ['fidži'] },
    { char: '🇫🇮', category: 'flagy', keywords: ['finsko'] },
    { char: '🇬🇦', category: 'flagy', keywords: ['gabon'] },
    { char: '🇬🇲', category: 'flagy', keywords: ['gambie'] },
    { char: '🇬🇪', category: 'flagy', keywords: ['gruzie'] },
    { char: '🇬🇭', category: 'flagy', keywords: ['ghana'] },
    { char: '🇬🇷', category: 'flagy', keywords: ['řecko'] },
    { char: '🇬🇩', category: 'flagy', keywords: ['grenada'] },
    { char: '🇬🇹', category: 'flagy', keywords: ['guatemala'] },
    { char: '🇬🇳', category: 'flagy', keywords: ['guinea'] },
    { char: '🇬🇼', category: 'flagy', keywords: ['guinea-bissau'] },
    { char: '🇬🇾', category: 'flagy', keywords: ['guyana'] },
    { char: '🇭🇹', category: 'flagy', keywords: ['haiti'] },
    { char: '🇭🇳', category: 'flagy', keywords: ['honduras'] },
    { char: '🇮🇸', category: 'flagy', keywords: ['island'] },
    { char: '🇮🇩', category: 'flagy', keywords: ['indonésie'] },
    { char: '🇮🇷', category: 'flagy', keywords: ['írán'] },
    { char: '🇮🇶', category: 'flagy', keywords: ['iráq'] },
    { char: '🇮🇪', category: 'flagy', keywords: ['irsko'] },
    { char: '🇮🇱', category: 'flagy', keywords: ['izrael'] },
    { char: '🇯🇲', category: 'flagy', keywords: ['jamajka'] },
    { char: '🇯🇴', category: 'flagy', keywords: ['jordánsko'] },
    { char: '🇰🇿', category: 'flagy', keywords: ['kazachstán'] },
    { char: '🇰🇪', category: 'flagy', keywords: ['keňa'] },
    { char: '🇰🇮', category: 'flagy', keywords: ['kiribati'] },
    { char: '🇰🇼', category: 'flagy', keywords: ['kuvajt'] },
    { char: '🇰🇬', category: 'flagy', keywords: ['kyrgyzstán'] },
    { char: '🇱🇦', category: 'flagy', keywords: ['laos'] },
    { char: '🇱🇻', category: 'flagy', keywords: ['lotyšsko'] },
    { char: '🇱🇧', category: 'flagy', keywords: ['libanon'] },
    { char: '🇱🇸', category: 'flagy', keywords: ['lesotho'] },
    { char: '🇱🇷', category: 'flagy', keywords: ['liberie'] },
    { char: '🇱🇾', category: 'flagy', keywords: ['libye'] },
    { char: '🇱🇮', category: 'flagy', keywords: ['lichtenštejnsko'] },
    { char: '🇱🇹', category: 'flagy', keywords: ['litva'] },
    { char: '🇱🇺', category: 'flagy', keywords: ['lucembursko'] },
    { char: '🇲🇬', category: 'flagy', keywords: ['madagaskar'] },
    { char: '🇲🇼', category: 'flagy', keywords: ['malawi'] },
    { char: '🇲🇾', category: 'flagy', keywords: ['malajsie'] },
    { char: '🇲🇻', category: 'flagy', keywords: ['maledivy'] },
    { char: '🇲🇱', category: 'flagy', keywords: ['mali'] },
    { char: '🇲🇹', category: 'flagy', keywords: ['malta'] },
    { char: '🇲🇭', category: 'flagy', keywords: ['marshallovy'] },
    { char: '🇲🇷', category: 'flagy', keywords: ['mauritánie'] },
    { char: '🇲🇺', category: 'flagy', keywords: ['mauricius'] },
    { char: '🇲🇽', category: 'flagy', keywords: ['mexiko'] },
    { char: '🇫🇲', category: 'flagy', keywords: ['mikronésie'] },
    { char: '🇲🇩', category: 'flagy', keywords: ['moldavsko'] },
    { char: '🇲🇳', category: 'flagy', keywords: ['mongolsko'] },
    { char: '🇲🇪', category: 'flagy', keywords: ['černá', 'hora'] },
    { char: '🇲🇦', category: 'flagy', keywords: ['maroko'] },
    { char: '🇲🇿', category: 'flagy', keywords: ['mosambik'] },
    { char: '🇲🇲', category: 'flagy', keywords: ['myanmar'] },
    { char: '🇳🇦', category: 'flagy', keywords: ['namibie'] },
    { char: '🇳🇷', category: 'flagy', keywords: ['nauru'] },
    { char: '🇳🇵', category: 'flagy', keywords: ['nepál'] },
    { char: '🇳🇱', category: 'flagy', keywords: ['nizozemsko'] },
    { char: '🇳🇿', category: 'flagy', keywords: ['nový', 'zéland'] },
    { char: '🇳🇮', category: 'flagy', keywords: ['nikaragua'] },
    { char: '🇳🇪', category: 'flagy', keywords: ['niger'] },
    { char: '🇳🇬', category: 'flagy', keywords: ['nigérie'] },
    { char: '🇰🇵', category: 'flagy', keywords: ['severní', 'korea'] },
    { char: '🇲🇰', category: 'flagy', keywords: ['severní', 'makedonie'] },
    { char: '🇳🇴', category: 'flagy', keywords: ['norsko'] },
    { char: '🇴🇲', category: 'flagy', keywords: ['omán'] },
    { char: '🇵🇰', category: 'flagy', keywords: ['pákistán'] },
    { char: '🇵🇼', category: 'flagy', keywords: ['palau'] },
    { char: '🇵🇸', category: 'flagy', keywords: ['palestina'] },
    { char: '🇵🇦', category: 'flagy', keywords: ['panama'] },
    { char: '🇵🇬', category: 'flagy', keywords: ['papua'] },
    { char: '🇵🇾', category: 'flagy', keywords: ['paraguay'] },
    { char: '🇵🇪', category: 'flagy', keywords: ['peru'] },
    { char: '🇵🇭', category: 'flagy', keywords: ['filipíny'] },
    { char: '🇵🇹', category: 'flagy', keywords: ['portugalsko'] },
    { char: '🇶🇦', category: 'flagy', keywords: ['katar'] },
    { char: '🇷🇴', category: 'flagy', keywords: ['rumunsko'] },
    { char: '🇷🇼', category: 'flagy', keywords: ['rwanda'] },
    { char: '🇰🇳', category: 'flagy', keywords: ['svatý', 'kitts'] },
    { char: '🇱🇨', category: 'flagy', keywords: ['svatá', 'lucie'] },
    { char: '🇻🇨', category: 'flagy', keywords: ['svatý', 'vincent'] },
    { char: '🇼🇸', category: 'flagy', keywords: ['samoa'] },
    { char: '🇸🇲', category: 'flagy', keywords: ['san', 'marino'] },
    { char: '🇸🇹', category: 'flagy', keywords: ['svatý', 'tomáš'] },
    { char: '🇸🇦', category: 'flagy', keywords: ['saúdská', 'arábie'] },
    { char: '🇸🇳', category: 'flagy', keywords: ['senegal'] },
    { char: '🇷🇸', category: 'flagy', keywords: ['srbsko'] },
    { char: '🇸🇨', category: 'flagy', keywords: ['seychely'] },
    { char: '🇸🇱', category: 'flagy', keywords: ['sierra', 'leone'] },
    { char: '🇸🇬', category: 'flagy', keywords: ['singapur'] },
    { char: '🇸🇮', category: 'flagy', keywords: ['slovinsko'] },
    { char: '🇸🇧', category: 'flagy', keywords: ['šalamounovy'] },
    { char: '🇸🇴', category: 'flagy', keywords: ['somálsko'] },
    { char: '🇸🇸', category: 'flagy', keywords: ['jižní', 'súdán'] },
    { char: '🇱🇰', category: 'flagy', keywords: ['srí', 'lanka'] },
    { char: '🇸🇩', category: 'flagy', keywords: ['súdán'] },
    { char: '🇸🇷', category: 'flagy', keywords: ['surinam'] },
    { char: '🇸🇪', category: 'flagy', keywords: ['švédsko'] },
    { char: '🇨🇭', category: 'flagy', keywords: ['švýcarsko'] },
    { char: '🇸🇾', category: 'flagy', keywords: ['sýrie'] },
    { char: '🇹🇼', category: 'flagy', keywords: ['tchaj-wan'] },
    { char: '🇹🇯', category: 'flagy', keywords: ['tádžikistán'] },
    { char: '🇹🇿', category: 'flagy', keywords: ['tanzanie'] },
    { char: '🇹🇭', category: 'flagy', keywords: ['thajsko'] },
    { char: '🇹🇱', category: 'flagy', keywords: ['východní', 'timor'] },
    { char: '🇹🇬', category: 'flagy', keywords: ['togo'] },
    { char: '🇹🇴', category: 'flagy', keywords: ['tonga'] },
    { char: '🇹🇹', category: 'flagy', keywords: ['trinidad'] },
    { char: '🇹🇳', category: 'flagy', keywords: ['tunisko'] },
    { char: '🇹🇷', category: 'flagy', keywords: ['turecko'] },
    { char: '🇹🇲', category: 'flagy', keywords: ['turkmenistán'] },
    { char: '🇹🇻', category: 'flagy', keywords: ['tuvalu'] },
    { char: '🇺🇬', category: 'flagy', keywords: ['uganda'] },
    { char: '🇺🇦', category: 'flagy', keywords: ['ukrajina'] },
    { char: '🇦🇪', category: 'flagy', keywords: ['emiráty'] },
    { char: '🇺🇾', category: 'flagy', keywords: ['uruguay'] },
    { char: '🇺🇿', category: 'flagy', keywords: ['uzbekistán'] },
    { char: '🇻🇺', category: 'flagy', keywords: ['vanuatu'] },
    { char: '🇻🇪', category: 'flagy', keywords: ['venezuela'] },
    { char: '🇻🇳', category: 'flagy', keywords: ['vietnam'] },
    { char: '🇾🇪', category: 'flagy', keywords: ['jemén'] },
    { char: '🇿🇲', category: 'flagy', keywords: ['zambie'] },
    { char: '🇿🇼', category: 'flagy', keywords: ['zimbabwe'] },
];

// Kategorie s ikonami a názvy
const categories = [
    { id: 'all', name: 'Vše', icon: '🎲' },
    { id: 'smajlici', name: 'Smajlíci', icon: '😀' },
    { id: 'srdce', name: 'Srdce', icon: '❤️' },
    { id: 'zvirata', name: 'Zvířata', icon: '🐶' },
    { id: 'jidlo', name: 'Jídlo', icon: '🍕' },
    { id: 'sport', name: 'Sport', icon: '⚽' },
    { id: 'doprava', name: 'Doprava', icon: '🚗' },
    { id: 'predmety', name: 'Předměty', icon: '📱' },
    { id: 'flagy', name: 'Vlajky', icon: '🏳️' }
];

export default function render(container) {
    clearElement(container);
    
    const wrapper = createElement('div', { className: 'copy-emoji-app-v2' });
    
    // Kategorie (horizontální scroll)
    const categoriesWrapper = createElement('div', { className: 'categories-wrapper' });
    const categoriesContainer = createElement('div', { className: 'categories-container' });
    
    let activeCategory = 'all';
    
    categories.forEach(cat => {
        const catBtn = createElement('button', {
            className: `category-btn ${cat.id === 'all' ? 'active' : ''}`,
            'data-category': cat.id
        });
        catBtn.innerHTML = `${cat.icon} ${cat.name}`;
        catBtn.addEventListener('click', () => {
            document.querySelectorAll('.category-btn').forEach(btn => btn.classList.remove('active'));
            catBtn.classList.add('active');
            activeCategory = cat.id;
            renderEmojis(searchInput.value, activeCategory);
        });
        categoriesContainer.appendChild(catBtn);
    });
    
    categoriesWrapper.appendChild(categoriesContainer);
    wrapper.appendChild(categoriesWrapper);
    
    // Vyhledávání
    const searchWrapper = createElement('div', { className: 'search-wrapper-v2' });
    const searchInput = createElement('input', {
        type: 'text',
        placeholder: '🔍 Hledat emoji česky nebo anglicky... (např. "pes", "smích", "láska")',
        className: 'search-input-v2'
    });
    searchWrapper.appendChild(searchInput);
    wrapper.appendChild(searchWrapper);
    
    // Počítadlo výsledků
    const statsBar = createElement('div', { className: 'stats-bar' });
    const resultCount = createElement('span', { className: 'result-count' });
    statsBar.appendChild(resultCount);
    wrapper.appendChild(statsBar);
    
    // Grid emoji
    const gridWrapper = createElement('div', { className: 'emoji-grid-wrapper' });
    const grid = createElement('div', { className: 'emoji-grid-v2' });
    gridWrapper.appendChild(grid);
    wrapper.appendChild(gridWrapper);
    
    container.appendChild(wrapper);
    
    // Funkce pro vyhledávání (česky + diakritika)
    function searchEmoji(query, category) {
        if (!query.trim()) {
            // Bez dotazu - jen kategorie
            return emojiDatabase.filter(emoji => category === 'all' || emoji.category === category);
        }
        
        const normalizedQuery = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
        
        return emojiDatabase.filter(emoji => {
            // Filtrování podle kategorie
            if (category !== 'all' && emoji.category !== category) return false;
            
            // Vyhledávání v klíčových slovech
            return emoji.keywords.some(keyword => {
                const normalizedKeyword = keyword.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
                return normalizedKeyword.includes(normalizedQuery);
            });
        });
    }
    
    // Renderování emoji
    function renderEmojis(query, category) {
        const results = searchEmoji(query, category);
        
        // Aktualizace počítadla
        const total = results.length;
        if (query.trim()) {
            resultCount.textContent = `🔍 Nalezeno ${total} emoji pro "${query}"`;
        } else {
            const categoryName = categories.find(c => c.id === category)?.name || 'Vše';
            resultCount.textContent = `📋 ${total} emoji v kategorii ${categoryName}`;
        }
        
        // Vyčištění gridu
        clearElement(grid);
        
        if (results.length === 0) {
            const noResults = createElement('div', { 
                className: 'no-results-v2',
                innerHTML: '❌ Žádné emoji nenalezeno<br><small>Zkus jiné slovo (např. "pes", "láska", "smích")</small>'
            });
            grid.appendChild(noResults);
            return;
        }
        
        // Vykreslení výsledků
        results.forEach(emoji => {
            const emojiCard = createElement('div', { className: 'emoji-card-v2' });
            const emojiChar = createElement('div', { 
                className: 'emoji-char-v2',
                text: emoji.char
            });
            const emojiHint = createElement('div', { 
                className: 'emoji-hint',
                text: emoji.keywords.slice(0, 2).join(', ')
            });
            
            emojiCard.appendChild(emojiChar);
            emojiCard.appendChild(emojiHint);
            
            emojiCard.addEventListener('click', async () => {
                await copyToClipboard(emoji.char);
                // Vizuální feedback
                emojiCard.style.transform = 'scale(0.95)';
                setTimeout(() => {
                    emojiCard.style.transform = '';
                }, 150);
            });
            
            grid.appendChild(emojiCard);
        });
    }
    
    // Vyhledávání při psaní (s debounce)
    let debounceTimer;
    searchInput.addEventListener('input', (e) => {
        clearTimeout(debounceTimer);
        debounceTimer = setTimeout(() => {
            renderEmojis(e.target.value, activeCategory);
        }, 300);
    });
    
    // Inicializace
    renderEmojis('', 'all');
}

export function cleanup() {
    console.log('Copy Emoji V2 app se zavírá');
}